version: '3'

services:
  server:
    build:
      context: ChallengeDashboard
    volumes:
      - ".:/app"
    links:
      - db
    ports:
      - "5000:80"
  db:
    image: postgres:13
    environment:
      - "POSTGRES_PASSWORD=x2o2!C1uBCh@l1nG3x"
    ports:
      - "5432:5432"